language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run start:test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: vr1KxIMA4HGObMGwTVeaYw  
  keep_history: true
  on:
    branch: develop